repo: 'content-semantics'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html

html:
  - path: 'index.html'
    has:
      - 'header'
      - check: 'header h1'
        message: 'There is no `<h1>` tag inside a `<header>` tag'
      - check: 'header nav'
        message: 'There is no `<nav>` tag inside a `<header>` tag'
      - check: 'header nav ol'
        message: 'There is no `<ol>` tag inside a `<nav>` tag, inside a `<header>` tag'
      - 'h2'
      - 'p'
      - 'blockquote'
      - check: 'blockquote cite'
        message: 'There’s no `<cite>` tag inside the `<blockquote>` tag'
      - 'q'
      - 'ul'
      - 'dl'
      - 'data'
      - 'time'
      - 'small'
      - 'strong'
      - 'em'
      - 'i'
      - 'b'
      - 'figure'
      - check: 'figure img'
        message: 'There is no `<img>` tag inside the `<figure>` tag'
      - check: 'figure figcaption'
        message: 'There is no `<figcaption>` tag inside the `<figure>` tag'
      - check: 'a[href]'
        message: 'There is no `href=""` attribute on the `<a>` tag'
      - 'aside'
      - 'footer'
    search:
      - 'Beetroot'
      - 'purple'
      - 'Battlestar Galactica'
      - 'Chioggia'
      - 'Carbohydrates'
      - 'Vegetable!'
      - 'Wikipedia'
